---
- name: nginx installation & service started
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    apt:
        name: package1
        state: latest
  - name: service nginx
    service:
        name: nginx
        state: started
