---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: bucketname1
      AccessControl: accessControl1
      VersioningConfiguration:
        Status: versioningConfiguration1
      LifecycleConfiguration:
        Rules:
          - Id: id1
            Prefix: logs
            Status: Enabled
            Transitions:
              - TransitionInDays: transitionInDays1
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: storageClass1
            ExpirationInDays: expirationInDays1 

